### ISSUE TITLE
Cards requirements control code review

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#81]
We need to carefully review all the cards requirements control code.
There are plenty of cases which can put the game into unplayable state.

Example:
If you play an "Aerobraked Ammonia Asteroid" card and there no card to put Microbes on - game will block with no options to recover.

It seems to be a long work, due to requirement to fix tests and write a lot of new.
But we really need to start it.

**Comment by alrusdi** [comment]
- [ ] Birds - allowed to be played even if no players with plant production, game will lock on player selection phase
- [ ] BlackPolarDust - minor, asks for a space to place an ocean even if no oceans available
- [ ] BusinessNetwork - minor, but if player has no money to buy card he should have only option to discard it
- [ ] Cartel - counts tags even on Event cards - it is incorrect
- [ ] CloudSeeding - allowed to be played even if no players with heat production, game will lock on player selection phase
- [ ] Comet - can lock game on player selection phase to remove plants if there no plants, does not provides options to not remove any plants, forces to select a space for ocean if there are no oceans available
- [ ] ConvoyFromEuropa - forces to select space for ocean if there are no oceans available
- [ ] DeimosDown - forces to select player to remove plants even if there no such players, does not provide an option to not remove any plants
- [ ] EnergyTapping - allowed to be played even if no players with energy production, game will lock on player selection phase
- [ ] EosChasmaNationalPark - forces to add animal to another card, if no such card, game will lock
- [ ] ExtremeColdFungus - has an option to add 2 Microbes to another card even if no such cards played
- [ ] Fish - allowed to be played even if no players with plant production, game will lock on player selection phase
- [ ] GHGProducingBacteria - has an action option to remove Microbes from it even if there no Microbes
- [ ] HeatTrappers - allowed to be played even if no players with heat production, game will lock on player selection phase
- [ ] Herbivores - allowed to be played even if no players with plants production, game will lock on player selection phase
- [ ] HiredRaiders - OrOptions nested in AndOptions it can cause a bug like with Sabotage #84
- [ ] IceAsteroid  - forces to select space for ocean if there are no oceans available
- [ ] IceCapMelting - forces to select space for ocean if there are no oceans available
- [ ] ImmigrantCity - forces to select space for city if there are no places for cities on the board
- [ ] ImportedHydrogen - OrOptions nested in AndOptions it can cause a bug like with Sabotage #84
- [ ] ImportedNitrogen - refactor logic? it is not easy to understand
- [ ] Insulation - shows SelectAmount if player has no heat production
- [ ] LandClaim - can lock if there no places to claim
- [ ] LargeConvoy  - OrOptions nested in AndOptions it can cause a bug like with Sabotage #84
- [ ] LocalHeatTrapping - has an option to add Animals even if there no Animal cards
- [ ] MiningExpedition - forces to select player to remove plants even if there no such players, does not provide an option to not remove any plants
- [ ] NaturalPreserve - forces to select a space for tile even if no such space available
- [ ] NitriteReducingBacteria - has an option to remove Microbes even if there are no Microbes on it
- [ ] NuclearZone - forces to select space for ешду if there are no such place on the Board

**Comment by vincentneko** [comment]
The game needs a getAvailableSpacesForCity as there are some placement rules for cities.

**Comment by alrusdi** [comment]
@vincentneko can you please implement it? Aslo it will be great if you take care about HiredRaiders, ImportedHydrogen and LargeConvoy cards. They may have the same bug as in Sabotage card described in #84

**Comment by vincentneko** [comment]
Yes, will try to do it when I have some time

**Comment by vincentneko** [comment]
Changes done in commit "Fix city spacing issue" on branch issue-81. Please review and merge if ok.

**Comment by alrusdi** [comment]
We are finally did it!
